# ----------------------------
# Makefile Options
# ----------------------------

NAME = i2c_test
DESCRIPTION = "I2C TEST"
COMPRESSED = NO

CFLAGS = -Wall -Wextra -Oz
CXXFLAGS = -Wall -Wextra -Oz

# ----------------------------

include $(shell cedev-config --makefile)
